const productImages = {
  pizzaBright: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=85",
  pizzaRustic: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=900&q=85",
  pizzaTable: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=85",
  burgerClassic: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85",
  burgerDark: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85",
  burgerFries: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85",
  fries: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85",
  potatoFries: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=900&q=85",
  loadedFries: "https://pub-aaa82e9851064d22b954c3ebbafc9ae6.r2.dev/legacy/webp/loaded-cheesy-bacon-fries-for-every-craving-qRw1BmG1F0CUfPyO-P-b2.webp",
  wrap: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85",
  taco: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=900&q=85",
  chocolateShake: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=85",
  bananaShake: "https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=900&q=85",
  combo: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=85",
};

const categories = [
  { id: "all", name: "Populares", img: productImages.combo },
  { id: "pizzas", name: "Pizzas", img: productImages.pizzaBright },
  { id: "burgers", name: "Hamburguesas", img: productImages.burgerClassic },
  { id: "papas", name: "Papas", img: productImages.loadedFries },
  { id: "wraps", name: "Wraps", img: productImages.wrap },
  { id: "mex", name: "Mexican Food", img: productImages.taco },
  { id: "batidos", name: "Batidos", img: productImages.chocolateShake },
];

const products = [
  {
    id: 1,
    name: "La Gorda Pit",
    desc: "Muzzarella, pepperoni, oliva y borde crocante.",
    price: 4200,
    category: "pizzas",
    img: productImages.pizzaBright,
    recommended: true,
  },
  {
    id: 2,
    name: "Q'Jamone",
    desc: "Jamon crudo, rucula, parmesano y salsa de la casa.",
    price: 5100,
    category: "pizzas",
    img: productImages.pizzaRustic,
  },
  {
    id: 3,
    name: "La Fugazzeta",
    desc: "Cebolla dorada, doble queso y lluvia de oregano.",
    price: 4700,
    category: "pizzas",
    img: productImages.pizzaTable,
  },
  {
    id: 4,
    name: "Picantovich",
    desc: "Jalapenos, salsa brava y queso ahumado.",
    price: 5400,
    category: "pizzas",
    img: productImages.pizzaBright,
    recommended: true,
  },
  {
    id: 5,
    name: "Americana",
    desc: "Doble carne, cheddar, pickles y ketchup casero.",
    price: 5600,
    category: "burgers",
    img: productImages.burgerClassic,
    recommended: true,
  },
  {
    id: 6,
    name: "Boom Burger",
    desc: "Bacon, cebolla crispy, barbacoa y cheddar fundido.",
    price: 6200,
    category: "burgers",
    img: productImages.burgerDark,
  },
  {
    id: 7,
    name: "De la Casa",
    desc: "Carne smash, provolone, tomate y mayo de ajo.",
    price: 5900,
    category: "burgers",
    img: productImages.burgerFries,
  },
  {
    id: 8,
    name: "Papas Gordo",
    desc: "Papas, cheddar, panceta crocante y verdeo.",
    price: 3900,
    category: "papas",
    img: productImages.loadedFries,
    recommended: true,
  },
  {
    id: 9,
    name: "Metele Huevos",
    desc: "Papas rusticas, huevo, alioli y lluvia de paprika.",
    price: 4300,
    category: "papas",
    img: productImages.potatoFries,
  },
  {
    id: 10,
    name: "Wrap Pollo Crunch",
    desc: "Pollo crispy, lechuga, tomate y salsa ranch.",
    price: 4500,
    category: "wraps",
    img: productImages.wrap,
  },
  {
    id: 11,
    name: "Taco Fuego",
    desc: "Carne especiada, pico de gallo y crema acida.",
    price: 4800,
    category: "mex",
    img: productImages.taco,
  },
  {
    id: 12,
    name: "Batido Chocolate",
    desc: "Chocolate intenso, crema y lluvia de cacao.",
    price: 3100,
    category: "batidos",
    img: productImages.chocolateShake,
  },
  {
    id: 13,
    name: "Batido Banana",
    desc: "Banana, dulce de leche y leche bien fria.",
    price: 3000,
    category: "batidos",
    img: productImages.bananaShake,
  },
  {
    id: 14,
    name: "Combo El Gordo",
    desc: "Pizza chica, papas cheddar y bebida.",
    price: 7900,
    category: "all",
    img: productImages.combo,
    recommended: true,
  },
];
